stages:
    - build
    - policy-scan

build_app:
    image: maven:3.6.3-openjdk-8
    stage: build
    script: 
        - mvn -f app clean package
    artifacts:
        paths:
            - app/target/verademo.war

veracode_policy_scan:
  image: veracode/api-wrapper-java:latest
  stage: policy-scan
  dependencies:
    - build_app
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - |
      java -jar /opt/veracode/api-wrapper.jar \
        -vid "${VERACODE_API_ID}" \
        -vkey "${VERACODE_API_KEY}" \
        -action UploadAndScan \
        -appname "VeraDemoJava3" \
        -createprofile true \
        -filepath app/target/verademo.war \
        -version "Commit ${CI_COMMIT_SHA:0:8} - Job $CI_JOB_ID"
  allow_failure: true