stages:
  - build
  - security

include:
  - project: 'devsecops7293510/gitlab-templates'
    ref: 'main'
    file: '/veracode/pipeline.yml'

variables:
  VERACODE_APP_NAME: "verademo-java-gitlab"
  PACKAGE_PATH: "app/target/*.war"
  PROJECT_PATH: "app"
  SANDBOX_NAME: "verademo-java-gitlab-sandbox"
  VERACODE_POLICY_NAME: "Veracode Recommended Very High + SCA"
  VERACODE_TEAMS: "Consultor"
#  USE_AUTOPACKAGE: "true"

############################
# BUILD
############################

# build:
#  image: maven:3.6.3-openjdk-8
#  stage: build
#  script:
#    - mvn -f app clean package
#  artifacts:
#    paths:
#      - app/target/verademo.war

